version: "2.1"

services:
  gl-mail-api-golang:
    container_name: gl-mail-api-golang
    image: gl-mail-api-golang
    build:
      context: .
      dockerfile: .docker/golang/Dockerfile
    env_file:
      - ./.docker/golang/.env
    ports:
      - "8002:8002"
