version: "3"

networks:
  ethernet:
    external: true

services:
  gl-mail-api-golang:
    container_name: gl-mail-api-golang
    image: gl-mail-api-golang
    build:
      context: .
      dockerfile: .docker/golang/Dockerfile
    volumes:
      - .:/go/src/github.com/Sharykhin/gl-mail-api
    env_file:
      - ./.docker/golang/.env
    ports:
      - "8002:8002"
    networks:
      - ethernet
